import type { IconType } from "react-icons";
import {
  SiCelery,
  SiCss,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiGin,
  SiGit,
  SiGithub,
  SiGo,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiKubernetes,
  SiMongodb,
  SiMui,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

export const techIcons: Record<string, IconType> = {
  python: SiPython,
  go: SiGo,
  typescript: SiTypescript,
  javascript: SiJavascript,
  html: SiHtml5,
  css: SiCss,
  fastapi: SiFastapi,
  gin: SiGin,
  nodejs: SiNodedotjs,
  expressjs: SiExpress,
  nextjs: SiNextdotjs,
  reactjs: SiReact,
  materialui: SiMui,
  tailwindcss: SiTailwindcss,
  postgresql: SiPostgresql,
  redis: SiRedis,
  rabbitmq: SiRabbitmq,
  mongodb: SiMongodb,
  celery: SiCelery,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  jenkins: SiJenkins,
  git: SiGit,
  github: SiGithub,
};
